In [2]:
list=['1',2,3,4,5]
for i in list:
    print(i)

1
2
3
4
5


In [3]:
import numpy

In [4]:
arr=numpy.array([1,2,3,4])

In [5]:
print(arr)

[1 2 3 4]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = numpy.array([[[5,6]], [[7,8]]])
print(arr[0,0,0])

5


In [8]:
arr = numpy.array([[[5,6,5,6]], [[7,8,7,8]]])
print(arr[0,0,3:-3:-1])
print(arr.ndim)

[6 5]
3


In [9]:
arr=numpy.array([1,2,3,4,8,9,0,8,1,2,3,4,8,9,0,8])
arr.reshape(2,2,2,2)

array([[[[1, 2],
         [3, 4]],

        [[8, 9],
         [0, 8]]],


       [[[1, 2],
         [3, 4]],

        [[8, 9],
         [0, 8]]]])

In [10]:
arr = numpy.array([[[5,6,5,6]], [[7,8,7,8]]])
arr.reshape(-1)

array([5, 6, 5, 6, 7, 8, 7, 8])

In [16]:
import numpy as np
arr1 = numpy.array([
    [1,2],
    [3,4]
])
arr2 = numpy.array([
    [5,6],
    [7,8]
])

In [15]:
output = numpy.concatenate((arr1,arr2),axis=1)
print(output, output.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [17]:
print(np.stack((arr1,arr2),axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
arr=numpy.array([[1,2,3,4],[5,6,7,8]])
index=np.searchsorted(arr,[6,1,2,3],'right')
print(index)

ValueError: object too deep for desired array